# Generated by Django 5.2.9 on 2025-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_readiness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='pdf_report_path',
        ),
        migrations.AddField(
            model_name='assessment',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
