# Generated by Django 5.2.9 on 2025-12-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_readiness', '0002_remove_assessment_pdf_report_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='pdf_report',
        ),
        migrations.AddField(
            model_name='assessment',
            name='pdf_report_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
